#!/bin/bash
#
# Starts Kometa Preview Studio using Docker Compose.
#
# This script verifies prerequisites, creates required directories and .env file
# if missing, downloads the Inter font if needed, builds and starts the containers.
#
# Requires: Bash, Docker with docker-compose

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Helper functions
info() { echo -e "${CYAN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err() { echo -e "${RED}[ERR] ${NC} $1"; }
success() { echo -e "${GREEN}[OK]  ${NC} $1"; }

# Determine repo root (scripts are in repo_root/scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

info "Changing to repository root: $REPO_ROOT"
cd "$REPO_ROOT"

# ============================================================
# Step 1: Verify Docker is available
# ============================================================
info "Checking Docker availability..."

if ! docker version >/dev/null 2>&1; then
    err "Docker is not available or Docker daemon is not running."
    err "Please install Docker and ensure it is running."
    err "Download: https://docs.docker.com/get-docker/"
    exit 1
fi
success "Docker is available"

# ============================================================
# Step 2: Verify docker-compose is available
# ============================================================
info "Checking docker-compose availability..."

if docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
elif docker-compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker-compose"
else
    err "docker-compose is not available."
    err "Please install Docker Compose."
    err "See: https://docs.docker.com/compose/install/"
    exit 1
fi
success "docker-compose is available (using: $COMPOSE_CMD)"

# ============================================================
# Step 3: Ensure required directories exist
# ============================================================
info "Ensuring required directories exist..."

mkdir -p "$REPO_ROOT/fonts"
mkdir -p "$REPO_ROOT/jobs"
mkdir -p "$REPO_ROOT/cache"

success "Required directories exist"

# ============================================================
# Step 4: Ensure .env exists with sensible defaults
# ============================================================
info "Checking .env configuration..."

ENV_FILE="$REPO_ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
    warn ".env file not found. Creating with default values..."

    cat > "$ENV_FILE" << 'EOF'
# Kometa Preview Studio - Environment Configuration
# Auto-generated by start.sh

# Backend server settings
PORT=3001
HOST=127.0.0.1
CORS_ORIGIN=http://localhost:5173

# Jobs and fonts directories (container paths)
JOBS_PATH=/app/jobs
FONTS_PATH=/app/fonts

# Kometa Docker image tag (pinned for deterministic rendering)
KOMETA_IMAGE_TAG=v2.2.2

# Renderer image name (built from ./renderer)
KOMETA_RENDERER_IMAGE=kometa-preview-renderer:latest
EOF

    success "Created .env with default configuration"
else
    success ".env file exists"
fi

# ============================================================
# Step 5: Fonts automation - download Inter if missing
# ============================================================
info "Checking for Inter font..."

INTER_FONT_PATH="$REPO_ROOT/fonts/Inter-Regular.ttf"

if [ ! -f "$INTER_FONT_PATH" ]; then
    warn "Inter-Regular.ttf not found. Attempting to download..."

    INTER_ZIP_URL="https://github.com/rsms/inter/releases/download/v4.0/Inter-4.0.zip"
    TEMP_DIR=$(mktemp -d)
    TEMP_ZIP="$TEMP_DIR/Inter-4.0.zip"

    cleanup() {
        rm -rf "$TEMP_DIR"
    }
    trap cleanup EXIT

    info "Downloading Inter font from GitHub..."

    if command -v curl >/dev/null 2>&1; then
        curl -L -o "$TEMP_ZIP" "$INTER_ZIP_URL"
    elif command -v wget >/dev/null 2>&1; then
        wget -O "$TEMP_ZIP" "$INTER_ZIP_URL"
    else
        err "Neither curl nor wget found. Cannot download Inter font."
        err ""
        err "Please manually add a font to the fonts/ directory:"
        err "  1. Download any .ttf or .otf font file"
        err "  2. Place it in: $REPO_ROOT/fonts"
        err "  3. Run this script again"
        err ""
        err "Recommended: Download Inter from https://github.com/rsms/inter/releases"
        exit 1
    fi

    info "Extracting Inter-Regular.ttf..."

    unzip -q "$TEMP_ZIP" -d "$TEMP_DIR"

    # Find and copy Inter-Regular.ttf
    EXTRACTED_FONT=$(find "$TEMP_DIR" -name "Inter-Regular.ttf" -type f | head -1)

    if [ -n "$EXTRACTED_FONT" ]; then
        cp "$EXTRACTED_FONT" "$INTER_FONT_PATH"
        success "Inter-Regular.ttf installed to fonts/"
    else
        err "Could not find Inter-Regular.ttf in the downloaded archive"
        exit 1
    fi
else
    success "Inter-Regular.ttf found"
fi

# ============================================================
# Step 6: Build and run Docker Compose
# ============================================================
info "Building Docker images (this may take a few minutes on first run)..."

$COMPOSE_CMD build
if [ $? -ne 0 ]; then
    err "docker-compose build failed"
    exit 1
fi
success "Docker images built successfully"

info "Starting services..."

$COMPOSE_CMD up -d
if [ $? -ne 0 ]; then
    err "docker-compose up failed"
    exit 1
fi
success "Services started"

info "Container status:"
$COMPOSE_CMD ps

# ============================================================
# Step 7: Print next actions
# ============================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Kometa Preview Studio is running!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Frontend UI:  http://localhost:5173"
echo "Backend API:  http://localhost:3001"
echo ""
echo "Next steps:"
echo "  - View logs:    ./scripts/logs.sh"
echo "  - Stop:         ./scripts/stop.sh"
echo "  - Full reset:   ./scripts/reset.sh"
echo ""
