<#
.SYNOPSIS
    Starts Kometa Preview Studio using Docker Compose.

.DESCRIPTION
    This script verifies prerequisites, creates required directories and .env file
    if missing, downloads the Inter font if needed, builds and starts the containers,
    and opens the UI in the default browser.

.NOTES
    Requires: Windows PowerShell 5.1+, Docker Desktop running
#>

$ErrorActionPreference = "Stop"

# Helper functions
function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Cyan
}

function Write-Warn {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Write-Err {
    param([string]$Message)
    Write-Host "[ERR]  $Message" -ForegroundColor Red
}

function Write-Success {
    param([string]$Message)
    Write-Host "[OK]   $Message" -ForegroundColor Green
}

# Determine repo root (scripts are in repo_root/scripts/)
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir

Write-Info "Changing to repository root: $RepoRoot"
Set-Location $RepoRoot

# ============================================================
# Step 1: Verify Docker is available
# ============================================================
Write-Info "Checking Docker availability..."

try {
    $dockerVersion = docker version 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Docker returned non-zero exit code"
    }
    Write-Success "Docker is available"
} catch {
    Write-Err "Docker is not available or Docker Desktop is not running."
    Write-Err "Please install Docker Desktop and ensure it is running."
    Write-Err "Download: https://www.docker.com/products/docker-desktop"
    exit 1
}

# ============================================================
# Step 2: Verify docker-compose is available
# ============================================================
Write-Info "Checking docker-compose availability..."

try {
    $composeVersion = docker-compose version 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "docker-compose returned non-zero exit code"
    }
    Write-Success "docker-compose is available"
} catch {
    Write-Err "docker-compose is not available."
    Write-Err "Docker Desktop typically includes docker-compose."
    Write-Err "Please ensure Docker Desktop is properly installed."
    exit 1
}

# ============================================================
# Step 3: Ensure required directories exist
# ============================================================
Write-Info "Ensuring required directories exist..."

$fontsDir = Join-Path $RepoRoot "fonts"
$jobsDir = Join-Path $RepoRoot "jobs"
$cacheDir = Join-Path $RepoRoot "cache"

if (-not (Test-Path $fontsDir)) {
    New-Item -ItemType Directory -Path $fontsDir -Force | Out-Null
    Write-Info "Created directory: fonts/"
}

if (-not (Test-Path $jobsDir)) {
    New-Item -ItemType Directory -Path $jobsDir -Force | Out-Null
    Write-Info "Created directory: jobs/"
}

if (-not (Test-Path $cacheDir)) {
    New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
    Write-Info "Created directory: cache/ (for TMDb/external API caching)"
}

Write-Success "Required directories exist"

# ============================================================
# Step 4: Ensure .env exists with sensible defaults
# ============================================================
Write-Info "Checking .env configuration..."

$envFile = Join-Path $RepoRoot ".env"

if (-not (Test-Path $envFile)) {
    Write-Warn ".env file not found. Creating with default values..."

    $envContent = @"
# Kometa Preview Studio - Environment Configuration
# Auto-generated by start.ps1

# Backend server settings
PORT=3001
HOST=127.0.0.1
CORS_ORIGIN=http://localhost:5173

# Jobs and fonts directories (container paths)
JOBS_PATH=/app/jobs
FONTS_PATH=/app/fonts

# Kometa Docker image tag (pinned for deterministic rendering)
KOMETA_IMAGE_TAG=v2.2.2

# Renderer image name (built from ./renderer)
KOMETA_RENDERER_IMAGE=kometa-preview-renderer:latest
"@

    $envContent | Out-File -FilePath $envFile -Encoding UTF8 -Force
    Write-Success "Created .env with default configuration"
} else {
    Write-Success ".env file exists"
}

# ============================================================
# Step 5: Fonts automation - download Inter if missing
# ============================================================
Write-Info "Checking for Inter font..."

$interFontPath = Join-Path $fontsDir "Inter-Regular.ttf"

if (-not (Test-Path $interFontPath)) {
    Write-Warn "Inter-Regular.ttf not found. Attempting to download..."

    $interZipUrl = "https://github.com/rsms/inter/releases/download/v4.0/Inter-4.0.zip"
    $tempZip = Join-Path $env:TEMP "Inter-4.0.zip"
    $tempExtract = Join-Path $env:TEMP "Inter-Extract"

    try {
        Write-Info "Downloading Inter font from GitHub..."

        # Clean up any previous temp files
        if (Test-Path $tempZip) { Remove-Item $tempZip -Force }
        if (Test-Path $tempExtract) { Remove-Item $tempExtract -Recurse -Force }

        # Download the zip file
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $interZipUrl -OutFile $tempZip -UseBasicParsing

        Write-Info "Extracting Inter-Regular.ttf..."

        # Create temp extraction directory
        New-Item -ItemType Directory -Path $tempExtract -Force | Out-Null

        # Extract the zip
        Expand-Archive -Path $tempZip -DestinationPath $tempExtract -Force

        # Find and copy Inter-Regular.ttf
        $extractedFont = Get-ChildItem -Path $tempExtract -Recurse -Filter "Inter-Regular.ttf" | Select-Object -First 1

        if ($extractedFont) {
            Copy-Item -Path $extractedFont.FullName -Destination $interFontPath -Force
            Write-Success "Inter-Regular.ttf installed to fonts/"
        } else {
            throw "Could not find Inter-Regular.ttf in the downloaded archive"
        }

    } catch {
        Write-Err "Failed to download Inter font: $_"
        Write-Err ""
        Write-Err "Please manually add a font to the fonts/ directory:"
        Write-Err "  1. Download any .ttf or .otf font file"
        Write-Err "  2. Place it in: $fontsDir"
        Write-Err "  3. Run this script again"
        Write-Err ""
        Write-Err "Recommended: Download Inter from https://github.com/rsms/inter/releases"
        exit 1
    } finally {
        # Cleanup temp files
        if (Test-Path $tempZip) { Remove-Item $tempZip -Force -ErrorAction SilentlyContinue }
        if (Test-Path $tempExtract) { Remove-Item $tempExtract -Recurse -Force -ErrorAction SilentlyContinue }
    }
} else {
    Write-Success "Inter-Regular.ttf found"
}

# ============================================================
# Step 6: Build and run Docker Compose
# ============================================================
Write-Info "Building Docker images (this may take a few minutes on first run)..."

docker-compose build
if ($LASTEXITCODE -ne 0) {
    Write-Err "docker-compose build failed"
    exit 1
}
Write-Success "Docker images built successfully"

Write-Info "Starting services..."

docker-compose up -d
if ($LASTEXITCODE -ne 0) {
    Write-Err "docker-compose up failed"
    exit 1
}
Write-Success "Services started"

Write-Info "Container status:"
docker-compose ps

# ============================================================
# Step 7: Open UI in default browser
# ============================================================
Write-Info "Opening UI in default browser..."

$uiUrl = "http://localhost:5173"

try {
    Start-Process $uiUrl
    Write-Success "Opened $uiUrl in default browser"
} catch {
    Write-Warn "Could not open browser automatically. Please navigate to: $uiUrl"
}

# ============================================================
# Step 8: Print next actions
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Kometa Preview Studio is running!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Frontend UI:  http://localhost:5173"
Write-Host "Backend API:  http://localhost:3001"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  - View logs:    .\scripts\logs.ps1   (or double-click scripts\logs.bat)"
Write-Host "  - Stop:         .\scripts\stop.ps1   (or double-click scripts\stop.bat)"
Write-Host "  - Full reset:   .\scripts\reset.ps1  (or double-click scripts\reset.bat)"
Write-Host ""
